# Generated by Copilot
from langgraph.graph import END, StateGraph, START, MessagesState
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver
from langchain_core.messages import SystemMessage
import os
from dotenv import load_dotenv

from calendar_agent.calendar_tools import calendar_tools
from calendar_agent.calendar_prompt import SYSTEM_PROMPT
from llm_factory import ChatGroq

load_dotenv()

llm = ChatGroq(
    model=os.getenv("OLLAMA_MODEL", "gpt-oss:20b"),
    temperature=0.0,
)

model_with_tools = llm.bind_tools(calendar_tools)


def call_model(state: MessagesState):
    messages = state["messages"]
    messages_for_llm = [SystemMessage(content=SYSTEM_PROMPT)] + messages
    response = model_with_tools.invoke(messages_for_llm)
    return {"messages": [response]}


def should_continue(state: MessagesState):
    messages = state["messages"]
    last_message = messages[-1]

    if getattr(last_message, "tool_calls", None):
        return "tools"

    return END


tool_node = ToolNode(calendar_tools)

builder = StateGraph(MessagesState)
builder.add_node("call_model", call_model)
builder.add_node("tools", tool_node)
builder.add_edge(START, "call_model")
builder.add_conditional_edges("call_model", should_continue, ["tools", END])
builder.add_edge("tools", "call_model")

memory = MemorySaver()
graph = builder.compile(checkpointer=memory)
