# Generated by Copilot
from pathlib import Path

from langchain_core.tools import tool

from local_tools import list_project_files, read_project_file

PROJECT_ROOT = Path(__file__).resolve().parents[1]


@tool
def find_information_tool(query: str, directory: str = ".", extension: str = "", max_results: int = 5) -> str:
    """Search project files for relevant text and return the best matching snippets."""
    if not query or not query.strip():
        return "Specifica una query per cercare le informazioni desiderate."

    list_result = list_project_files.invoke({
        "directory": directory,
        "extension": extension,
        "recursive": True,
    })

    if list_result.startswith(("La cartella", "Nessun", "Errore")):
        return list_result

    files = [line.strip() for line in list_result.splitlines() if line.strip()]
    matches = []
    lower_query = query.lower()

    for relative_path in files:
        try:
            contents = read_project_file.invoke({"relative_path": relative_path})
        except Exception:
            continue

        if not isinstance(contents, str):
            continue

        lowered = contents.lower()
        if lower_query not in lowered:
            continue

        idx = lowered.index(lower_query)
        start = max(0, idx - 180)
        end = min(len(contents), idx + 260)
        snippet = contents[start:end].replace("\n", " ").strip()
        matches.append(f"File: {relative_path}\nSnippet: {snippet}\n---")

        if len(matches) >= max_results:
            break

    if not matches:
        return "Nessuna informazione rilevante trovata nei file locali."

    return "\n\n".join(matches)


@tool
def read_document_tool(relative_path: str) -> str:
    """Read a project file and return its text content, useful for direct analysis."""
    return read_project_file.invoke({"relative_path": relative_path})


@tool
def create_word_note_tool(title: str, notes: str, filename: str = "document_note.docx") -> str:
    """Create a Word note in the project root when the user asks to save findings."""
    if not title.strip():
        return "Specifica un titolo per il file Word."

    output_path = PROJECT_ROOT / filename
    safe_text = notes.strip() or "Nessuna nota da salvare."

    try:
        from docx import Document

        document = Document()
        document.add_heading(title.strip(), level=1)
        document.add_paragraph(safe_text)
        document.save(str(output_path))
        return f"Nota salvata in Word: {output_path}"
    except Exception:
        fallback_path = PROJECT_ROOT / filename.replace(".docx", ".txt")
        fallback_path.write_text(safe_text, encoding="utf-8")
        return f"Il pacchetto python-docx non è disponibile; ho salvato il contenuto in testo semplice: {fallback_path}"


calendar_tools = [
    find_information_tool,
    read_document_tool,
    create_word_note_tool,
]
