# Generated by Copilot
# This file defines the stable local-first tool layer and the optional external integrations.
import os

from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
from local_tools import calculator_tool, system_status_tool, list_project_files, read_project_file


LOCAL_CORE_TOOLS = [
    calculator_tool,
    system_status_tool,
    list_project_files,
    read_project_file,
]


def _service_available(service_name: str, env_key: str | None = None, credential_paths: tuple[str, ...] = ()) -> bool:
    """Return whether an optional integration is configured and ready to use."""
    if env_key and os.getenv(env_key):
        return True

    for path in credential_paths:
        if os.path.exists(path):
            return True

    return False


@tool
def search_agent_tool(query: str, thread_id: str = "search_thread") -> str:
    """Uses the web search agent only when the external search credential is configured."""
    if not _service_available("search", env_key="TAVILY_API_KEY"):
        return "Search agent is unavailable. The local-first assistant remains available without external search; provide a local file or ask for a local analysis instead."

    from search_agent.search_graph import create_search_graph

    search_app = create_search_graph()
    config = {"configurable": {"thread_id": thread_id}}
    state = {"messages": [HumanMessage(content=query)]}
    result = search_app.invoke(state, config=config)
    return result["messages"][-1].content


@tool
def document_agent_tool(query: str, thread_id: str = "document_thread") -> str:
    """Uses the local document-analysis path as the default operational analysis tool."""
    local_summary = (
        "Local document analysis is available through the project file tools. "
        "Use file listing and file reading to inspect the relevant files, then summarize the content."
    )

    # The core local tools already cover file reading and listing; keep the document path lightweight.
    return local_summary + f" Requested analysis: {query}"


@tool
def calendar_agent_tool(query: str, thread_id: str = "calendar_thread") -> str:
    """Legacy name retained for compatibility; in the current local-first phase, calendar access is optional and not required."""
    if not _service_available("calendar", credential_paths=("calendar_agent/credentials.json", "calendar_agent/token.json")):
        return "Calendar agent is not configured in this local setup. The default local workflow is document analysis and approved local tools."

    from calendar_agent.calendar_graph import graph as calendar_app

    config = {"configurable": {"thread_id": thread_id}}
    state = {"messages": [HumanMessage(content=query)]}
    result = calendar_app.invoke(state, config=config)
    return result["messages"][-1].content


@tool
def email_agent_tool(query: str, thread_id: str = "email_thread") -> str:
    """Email access is optional and must not block the main local flow."""
    if not _service_available("gmail", credential_paths=("email_agent/credentials.json", "email_agent/token.json")):
        return "Email agent is unavailable because Gmail credentials are not configured. The local workflow continues without it."

    from email_agent.email_connector import fetch_emails
    from email_agent.agent.email_graph import graph as email_app

    recent_emails = fetch_emails()
    config = {"configurable": {"thread_id": thread_id}}
    state = {
        "emails": recent_emails,
        "messages": [HumanMessage(content=query)],
        "revision_count": 0,
    }
    result = email_app.invoke(state, config=config)
    return result["messages"][-1].content


OPTIONAL_AGENT_TOOLS = [
    search_agent_tool,
    document_agent_tool,
    email_agent_tool,
    calendar_agent_tool,
]

# Core local tools remain the default, stable base for the supervisor.
# Optional agent tools are enabled only when their integrations are available and safe.
supervisor_tools = LOCAL_CORE_TOOLS + OPTIONAL_AGENT_TOOLS

