# Generated by Copilot
import os

from dotenv import load_dotenv
from langchain_core.messages import SystemMessage
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver

from email_agent.agent.email_state import AgentState
from email_agent.agent.email_prompt import SYSTEM_PROMPT
from email_agent.tools.list_emails import list_emails, create_daily_email_report_tool, create_quote_tool
from email_agent.tools.summariser import summarize_email
from llm_factory import ChatGroq

load_dotenv()

# Local, document-like email workflow: read, summarize, report, and estimate.
tools = [
    list_emails,
    summarize_email,
    create_daily_email_report_tool,
    create_quote_tool,
]

llm = ChatGroq(
    model=os.getenv("OLLAMA_MODEL", "gpt-oss:20b"),
    temperature=0.0,
)
model = llm.bind_tools(tools)


def call_model(state: AgentState):
    messages = state["messages"]
    messages_to_invoke = [SystemMessage(content=SYSTEM_PROMPT)] + messages
    response = model.invoke(messages_to_invoke)
    return {"messages": [response]}


def should_continue(state: AgentState):
    messages = state["messages"]
    last_message = messages[-1]

    if hasattr(last_message, "tool_calls") and len(last_message.tool_calls) > 0:
        return "tools"

    return END


tool_node = ToolNode(tools)
workflow = StateGraph(AgentState)
workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)
workflow.add_edge(START, "agent")
workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
workflow.add_edge("tools", "agent")

memory = MemorySaver()
graph = workflow.compile(checkpointer=memory)
