# Generated by Copilot
from pathlib import Path
from typing import Annotated

from langgraph.prebuilt import InjectedState
from langchain_core.tools import tool


@tool
def list_emails(state: Annotated[dict, InjectedState], max_results: int = 10) -> str:
    """List the emails currently available in the agent state."""
    emails = state.get("emails", [])
    if not emails:
        return "No recent emails found in the current state."

    emails_to_list = emails[:max_results]
    formatted_emails = []
    for idx, email in enumerate(emails_to_list):
        email_id = email.get("id", "N/A")
        subject = email.get("subject", "No Subject")
        sender = email.get("from", "Unknown Sender")
        date = email.get("date", "Unknown Date")
        formatted_emails.append(
            f"{idx + 1}. ID: {email_id}\n   From: {sender}\n   Date: {date}\n   Subject: {subject}\n"
        )

    return "\n".join(formatted_emails)


@tool
def create_daily_email_report_tool(state: Annotated[dict, InjectedState], filename: str = "daily_email_report.docx") -> str:
    """Create a daily summary report from the current inbox state and save it to a document."""
    emails = state.get("emails", [])
    if not emails:
        return "No email data available to generate a daily report."

    lines = ["Daily email report", "=================="]
    for idx, email in enumerate(emails[:10], start=1):
        subject = email.get("subject", "No Subject")
        sender = email.get("from", "Unknown Sender")
        date = email.get("date", "Unknown Date")
        body = (email.get("body") or "").strip().replace("\n", " ")
        lines.append(f"{idx}. {date} - {sender}\n   Subject: {subject}\n   Preview: {body[:220]}")

    report_text = "\n\n".join(lines)
    output_path = Path(__file__).resolve().parents[2] / filename

    try:
        from docx import Document

        document = Document()
        document.add_heading("Daily email report", level=1)
        for paragraph in report_text.splitlines():
            document.add_paragraph(paragraph)
        document.save(str(output_path))
        return f"Daily email report saved at: {output_path}"
    except Exception:
        fallback_path = output_path.with_suffix(".txt")
        fallback_path.write_text(report_text, encoding="utf-8")
        return f"The report was saved as text because python-docx is not installed: {fallback_path}"


@tool
def create_quote_tool(scope: str, estimated_hours: float = 0.0, hourly_rate: float = 0.0, currency: str = "EUR") -> str:
    """Create a preliminary quote draft for a service scope. The quote is a placeholder until pricing rules are defined."""
    if not scope or not scope.strip():
        return "Specificare il scope del lavoro per generare un preventivo iniziale."

    if estimated_hours > 0 and hourly_rate > 0:
        total = estimated_hours * hourly_rate
        return (
            f"Preventivo preliminare\n"
            f"Scope: {scope}\n"
            f"Stima ore: {estimated_hours}\n"
            f"Tariffa oraria: {hourly_rate} {currency}\n"
            f"Totale stimato: {total:.2f} {currency}\n\n"
            "Nota: questa è una stima iniziale; va confermata con i dettagli definitivi del lavoro."
        )

    return (
        f"Preventivo preliminare\n"
        f"Scope: {scope}\n\n"
        "Nota: il preventivo è ancora da definire in modo preciso. Indicare ore, tariffa e dettaglio del lavoro per completarlo."
    )
